# Numpy :: SVD
## SVD = Singular Value Decomposition

https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

* Author: Pochung Chen
* Email: pcchen@phys.nthu.edu.tw
* Last updated on 4/11/2022

In [1]:
import numpy as np
print(np.__version__)

1.22.3


## SVD of a $(2,2)$ matrix

$$ \Large
  M = U \Sigma V^\dagger.
$$

### Perform SVD

In [2]:
# SVD of a 2X2 matrix
M = np.array([[1, 2],
              [3, 4]])
print('[M]=\n', M)

U,S,Vd = np.linalg.svd(M)
print('[U]=\n', U)
print('S=\n', S)
print('[Vd]=\n', Vd)

[M]=
 [[1 2]
 [3 4]]
[U]=
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S=
 [5.4649857  0.36596619]
[Vd]=
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


### Check

In [3]:
# this gives the wrong answer because S is a vector
print('[U] S [Vd]=\n', U @ S @ Vd)

[U] S [Vd]=
 [-2.49789853  4.87447463]


### You can convert a vector to a diagonal matrix by `numpy.diag(vector)`

In [4]:
# convert S to a diagonal matrix and check again
print('[S]=\n', np.diag(S))
print('[U] [S] [Vd]=\n', U @ np.diag(S) @ Vd)

[S]=
 [[5.4649857  0.        ]
 [0.         0.36596619]]
[U] [S] [Vd]=
 [[1. 2.]
 [3. 4.]]


### Orthogonal conditions
* $U^\dagger U=I$
* $V^\dagger V=I$

In [5]:
Ud = np.transpose(U)
print('[Ud] [U]=\n', Ud @ U)
print('[U] [Ud]=\n', U @ Ud)

V = np.transpose(Vd)
print('[Vd] [V]=\n', Vd @ V)
print('[V] [Vd]=\n', V @ Vd)

[Ud] [U]=
 [[1.00000000e+00 9.98502693e-17]
 [9.98502693e-17 1.00000000e+00]]
[U] [Ud]=
 [[1.00000000e+00 3.00701513e-16]
 [3.00701513e-16 1.00000000e+00]]
[Vd] [V]=
 [[1.000000e+00 1.145223e-18]
 [1.145223e-18 1.000000e+00]]
[V] [Vd]=
 [[ 1.000000e+00 -1.145223e-18]
 [-1.145223e-18  1.000000e+00]]


## SVD of a $(4,2)$ matrix

In [6]:
# SVD of a 4X2 matrix
M = np.array(range(8))
# print('M=\n', M)
M = np.reshape(M, (4, 2))
print('[M]=\n',M)

U,S,Vd = np.linalg.svd(M)
print('[U]=\n', U)
print('S=\n', S)
print('[Vd]=\n', Vd)

[M]=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
[U]=
 [[-0.0656451  -0.83408076 -0.38578674 -0.38880405]
 [-0.30394881 -0.45564802  0.22458489  0.80595386]
 [-0.54225252 -0.07721528  0.70819044 -0.44549557]
 [-0.78055624  0.30121746 -0.54698859  0.02834576]]
S=
 [11.80788803  0.75748278]
[Vd]=
 [[-0.63180182 -0.77512996]
 [ 0.77512996 -0.63180182]]


### Check

In [7]:
# this fails because full matrices is set to be True
print('[U] [S] [Vd]=\n', U @ np.diag(S) @ Vd)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

### Set `full_matrices=False`

In [8]:
U,S,Vd = np.linalg.svd(M, full_matrices=False)
print('[M]=\n',M)
print('[U]=\n', U)
print('[S]=\n', S)
print('[Vd]=\n', Vd)

# check
print('[U] [S] [Vd]=\n', U @ np.diag(S) @ Vd)

[M]=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
[U]=
 [[-0.0656451  -0.83408076]
 [-0.30394881 -0.45564802]
 [-0.54225252 -0.07721528]
 [-0.78055624  0.30121746]]
[S]=
 [11.80788803  0.75748278]
[Vd]=
 [[-0.63180182 -0.77512996]
 [ 0.77512996 -0.63180182]]
[U] [S] [Vd]=
 [[-2.23890725e-18  1.00000000e+00]
 [ 2.00000000e+00  3.00000000e+00]
 [ 4.00000000e+00  5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00]]


### Orthogonal conditions
* $U^\dagger U=I$
* $V^\dagger V=I$

In [9]:
Ud = np.transpose(U)
print('[Ud] [U]=\n', Ud @ U)
print('[U] [Ud]=\n', U @ Ud)

V = np.transpose(Vd)
print('[Vd] [V]=\n', Vd @ V)
print('[V] [Vd]=\n', V @ Vd)

[Ud] [U]=
 [[ 1.00000000e+00 -2.91379687e-17]
 [-2.91379687e-17  1.00000000e+00]]
[U] [Ud]=
 [[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]
[Vd] [V]=
 [[ 1.00000000e+00 -5.98676349e-18]
 [-5.98676349e-18  1.00000000e+00]]
[V] [Vd]=
 [[1.00000000e+00 5.98676349e-18]
 [5.98676349e-18 1.00000000e+00]]


## SVD of a 2X4 matrix

In [10]:
# SVD of a 4X2 matrix
M = np.array(range(8))
# print('M=\n', M)
M = np.reshape(M, (2, 4))
print('[M]=\n',M)

U,S,Vd = np.linalg.svd(M)
print('[U]=\n', U)
print('[S]=\n', S)
print('[Vd]=\n', Vd)

[M]=
 [[0 1 2 3]
 [4 5 6 7]]
[U]=
 [[-0.29370412 -0.95589638]
 [-0.95589638  0.29370412]]
[S]=
 [11.73352876  1.52456641]
[Vd]=
 [[-0.32586834 -0.43236661 -0.53886488 -0.64536315]
 [ 0.77059057  0.33624265 -0.09810528 -0.5324532 ]
 [-0.38578674  0.22458489  0.70819044 -0.54698859]
 [-0.38880405  0.80595386 -0.44549557  0.02834576]]


### Check

In [11]:
# this fails because full matrices is set to be True
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

### Set `full_matrices=False`

In [12]:
U,S,Vd = np.linalg.svd(M, full_matrices=False)
print('U=\n', U)
print('S=\n', S)
print('Vd=\n', Vd)

# check
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

U=
 [[-0.29370412 -0.95589638]
 [-0.95589638  0.29370412]]
S=
 [11.73352876  1.52456641]
Vd=
 [[-0.32586834 -0.43236661 -0.53886488 -0.64536315]
 [ 0.77059057  0.33624265 -0.09810528 -0.5324532 ]]
U [S] Vd=
 [[-1.87949788e-15  1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 4.00000000e+00  5.00000000e+00  6.00000000e+00  7.00000000e+00]]


### Orthogonal conditions
* $U^\dagger U=I$
* $V^\dagger V=I$

In [13]:
Ud = np.transpose(U)
print('[Ud] [U]=\n', Ud @ U)
print('[U] [Ud]=\n', U @ Ud)

V = np.transpose(Vd)
print('[Vd] [V]=\n', Vd @ V)
print('[V] [Vd]=\n', V @ Vd)

[Ud] [U]=
 [[ 1.00000000e+00 -2.43462366e-16]
 [-2.43462366e-16  1.00000000e+00]]
[U] [Ud]=
 [[ 1.00000000e+00 -3.64188934e-16]
 [-3.64188934e-16  1.00000000e+00]]
[Vd] [V]=
 [[ 1.00000000e+00 -1.96801439e-16]
 [-1.96801439e-16  1.00000000e+00]]
[V] [Vd]=
 [[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


## SVD truncation and matrix approximation
* If we throw away some small singular values, we can constrauct an approximated matrix.

In [14]:
D = 6
M = np.random.rand(D,D)
print('[M]=\n', M)

U,S,Vd = np.linalg.svd(M)
print('[S]=\n', S)

for D_cut in range(1,D+1):
    print('D_cut =', D_cut)
    S_cut = np.zeros_like(S)
    S_cut[:D_cut] = S[:D_cut]
    print('S_cut=\n', S_cut)    
    Diff = U @ np.diag(S_cut) @ Vd - M
    print('Max Diff =', np.max(Diff))
    print()


[M]=
 [[0.69410316 0.84012354 0.75683882 0.17794192 0.26219273 0.47812639]
 [0.44400416 0.46315277 0.37900007 0.69793239 0.48037042 0.24613184]
 [0.80930596 0.29757193 0.4801326  0.61896992 0.10227588 0.75169913]
 [0.76844611 0.05039736 0.303347   0.28459688 0.22635832 0.0459779 ]
 [0.47804271 0.0512339  0.70040227 0.73353548 0.23587167 0.11879827]
 [0.43414966 0.22298451 0.67150494 0.81349836 0.13724415 0.21810445]]
[S]=
 [2.75037051 0.81821451 0.55277742 0.4724613  0.38853444 0.09132439]
D_cut = 1
S_cut=
 [2.75037051 0.         0.         0.         0.         0.        ]
Max Diff = 0.45550144090050715

D_cut = 2
S_cut=
 [2.75037051 0.81821451 0.         0.         0.         0.        ]
Max Diff = 0.17084805789356655

D_cut = 3
S_cut=
 [2.75037051 0.81821451 0.55277742 0.         0.         0.        ]
Max Diff = 0.261797375825578

D_cut = 4
S_cut=
 [2.75037051 0.81821451 0.55277742 0.4724613  0.         0.        ]
Max Diff = 0.23302600839207732

D_cut = 5
S_cut=
 [2.75037051 0.818

In [15]:
D = 8
M = np.array(range(D*D))
M = np.random.rand(D,D)
M = np.reshape(M, (D, D))
with np.printoptions(precision=2, linewidth=100):
    print('M=\n', M)

U,S,Vd = np.linalg.svd(M)
with np.printoptions(precision=2, linewidth=100):
    print('S=\n', S)

for D_cut in range(1,D+1):
    print('D_cut =', D_cut)
    S_cut = np.zeros_like(S)
    S_cut[:D_cut] = S[:D_cut]
    with np.printoptions(precision=2, linewidth=100):
        print('S_cut=\n', S_cut)    
    Diff = U @ np.diag(S_cut) @ Vd - M
    print('Max Diff =', np.max(Diff))
    with np.printoptions(precision=2, linewidth=100):
        print(U @ np.diag(S_cut) @ Vd)
    print()



M=
 [[0.03 0.52 0.58 0.03 0.82 0.83 0.57 0.47]
 [0.41 0.57 0.99 0.4  0.75 0.53 0.25 0.6 ]
 [0.78 0.75 0.23 0.41 0.97 0.72 0.01 0.32]
 [0.12 0.16 0.97 0.3  0.26 0.48 0.42 0.28]
 [0.4  0.94 0.23 0.02 0.3  0.72 0.91 0.1 ]
 [0.94 0.62 0.25 0.74 0.84 0.63 0.14 0.24]
 [0.2  0.16 0.97 0.31 0.84 0.33 0.41 0.35]
 [0.82 0.15 0.7  0.63 0.63 0.96 0.34 0.21]]
S=
 [4.12 1.32 1.14 0.73 0.47 0.33 0.14 0.08]
D_cut = 1
S_cut=
 [4.12 0.   0.   0.   0.   0.   0.   0.  ]
Max Diff = 0.4506863272505986
[[0.49 0.48 0.59 0.37 0.69 0.65 0.36 0.32]
 [0.55 0.54 0.67 0.41 0.78 0.74 0.4  0.36]
 [0.53 0.52 0.65 0.4  0.75 0.71 0.39 0.35]
 [0.36 0.36 0.44 0.27 0.51 0.49 0.27 0.24]
 [0.43 0.42 0.52 0.32 0.6  0.57 0.31 0.28]
 [0.54 0.53 0.65 0.4  0.76 0.72 0.39 0.35]
 [0.45 0.44 0.55 0.34 0.63 0.6  0.33 0.3 ]
 [0.55 0.55 0.67 0.42 0.78 0.74 0.4  0.36]]

D_cut = 2
S_cut=
 [4.12 1.32 0.   0.   0.   0.   0.   0.  ]
Max Diff = 0.42673750305947244
[[0.3  0.39 0.83 0.3  0.66 0.62 0.46 0.38]
 [0.39 0.46 0.88 0.35 0.75 0.71 0.4